Allow to disable warning dialog for unsaved files when linting
errata-ai/vale-vscode pull request #104
Opened 2022-09-09 07:41 UTC by apupier

![doNotShowDaialogAgain](https://user-images.githubusercontent.com/1105127/189298090-81e58591-7bdd-4875-896c-00dc07ab65ea.gif)

fixes #101

2022-09-14 21:49 UTC, jdkato approved these changes

2022-09-20 08:35 UTC, ChrisChinchilla commented
@apupier and @jdkato I've been travelling with quite poor internet, will check tomorrow and also bring back the quick actions functionality and we can then make a new release.

2022-09-22 07:53 UTC, ChrisChinchilla commented on package.json
> +        "vale.doNotShowAgainWarningForFileToBeSavedBeforeLinting": {
```suggestion
        "vale.doNotShowWarningForFileToBeSavedBeforeLinting": {
```

2022-09-22 07:59 UTC, ChrisChinchilla commented on package.json
> +          "description": "Do not show warning dialog that a file must be saved to have linting."
```suggestion
          "description": "Do not show warning dialog that a file must be saved to be linted."
```

2022-09-22 08:00 UTC, ChrisChinchilla commented on src/features/vsUtils.ts
> +    const shouldIgnore = config.get<boolean>('doNotShowAgainWarningForFileToBeSavedBeforeLinting') === true;
```suggestion
    const shouldIgnore = config.get<boolean>('doNotShowWarningForFileToBeSavedBeforeLinting') === true;
```

2022-09-22 08:00 UTC, ChrisChinchilla commented on src/features/vsUtils.ts
> +      await config.update('doNotShowAgainWarningForFileToBeSavedBeforeLinting', true, true);
```suggestion
      await config.update('doNotShowWarningForFileToBeSavedBeforeLinting', true, true);
```

2022-09-22 08:02 UTC, ChrisChinchilla requested changes
Made small suggestions on changing the variable to something clearer. I also cannot replicate the issue that made the need for this fix, but it doesn't seem to affect anything negatively, so, I guess it's fine to include :)

2022-09-29 05:41 UTC, merged