Rework action code
errata-ai/vale-vscode pull request #108
Opened 2022-10-01 13:23 UTC by ChrisChinchilla

2022-10-05 21:06 UTC, jdkato requested changes

2022-10-13 06:35 UTC, ChrisChinchilla commented on src/features/vsProvider.ts
> +    if (alert.Action.Name !== "suggest" && alert.Action.Params !== null) {
@jdkato Hmm, I'm confused, I checked `remove` actions and they worked, I was trying to find a way to handle the (many) rules that have no actions defined, maybe I could check for a null name instead I guess.

2022-10-13 06:36 UTC, ChrisChinchilla commented on src/features/vsProvider.ts
> -    if (diagnostic === undefined) {
@jdkato I am not familiar with that error, any reference so I can test it?

2022-10-13 06:54 UTC, jdkato commented on src/features/vsProvider.ts
> -    if (diagnostic === undefined) {
It's the one you mentioned in the Slack DM. You should see it in the developer console.

2022-10-13 06:55 UTC, jdkato commented on src/features/vsProvider.ts
> +    if (alert.Action.Name !== "suggest" && alert.Action.Params !== null) {
Something like:

```yaml
action:
  name: remove
```

2022-10-15 10:57 UTC, ChrisChinchilla commented
OK @jdkato Try the latest changes. it also made me realise that a seperate change is to go through a lot of the older rules and add actions to them. Once this is merged I'll also look at spelling.

2022-10-19 01:27 UTC, jdkato approved these changes

2022-10-19 01:28 UTC, jdkato commented
Looks good. I'm going to test it a few days before I make a release, just to be sure.

2022-10-19 01:28 UTC, merged

2022-10-19 09:51 UTC, ChrisChinchilla commented
@jdkato Sure, we can even squeeze some other features in to a release too. I'l' also slowly start updating rules with actions.